version: '3'

services:
  alpha:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile-alpha
    ports:
      - 65412:65412
    volumes:
      - "./:/app"
    networks:
      - gjk-network
  beta:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile-beta
    ports:
      - "${APP_PORT}:5000"
    volumes:
      - "./:/app"
    env_file:
      - .env
    networks:
      - gjk-network
  database:
    image: mysql:8
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - "$PWD/mysql_data_gjk_latest:/var/lib/mysql"
    entrypoint:
      - docker-entrypoint.sh
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - gjk-network
networks:
  gjk-network:
    name: gjk-network
